### ISSUE TITLE
Test card numbers for unsuccessful verifications creating successful transaction

### ISSUE THREAD

**Issue by zackspear** [KuriousAgency/commerce-braintree#10]
Hey there, we're very close to going live with the plugin so naturally we've been doing some thorough testing. When testing Braintree's ["Card numbers for unsuccessful verification"](https://developers.braintreepayments.com/guides/credit-cards/testing-go-live/php#card-numbers-for-unsuccessful-verification) I'm getting a successful transaction – redirected to the thank you page with order details and in the CMS the transaction has a status of "Success".

I wouldn't imagine this to be what's supposed to happen. Or am I missing something here?

Any insight would be great. 

Thanks in advance 🙏

**Comment by mcjackson18** [comment]
Hi @zackspear, the link you sent is only for verifying cards (which is different to creating a transaction). To test unsuccessful transactions you will need to adjust the amount as outlined here - [Testing Transaction amounts](https://developers.braintreepayments.com/reference/general/testing/php#transaction-amounts)

**Comment by zackspear** [comment]
😅 ah good case of RTFM. First time working with Braintree and it's mostly solo work. 

Cheers @mcjackson18
