### ISSUE TITLE
Error setting up Drop-in

### ISSUE THREAD

**Issue by focalinteractive** [KuriousAgency/commerce-braintree#20]
Hello,

We're trying to setup a test in to use Braintree using the plug-in. The initialisation of the drop-in fails with a PayPal-related error "A linked PayPal Sandbox account is required to use PayPal ". We don't want to use Paypal anyway so is there a way to disable that initialisation?

The documentation mentions a `getPaymentFormHtml()` method that can be used to customise the initialisation of the drop-in. How can we access this method? Is it a javascript method, is it available in the plug-in's php files?

Apologies for the newbie questions. Looking forward to your help.

**Comment by mcjackson18** [comment]
Hi @focalinteractive,

Please can you check that PayPal is disabled in your Braintree control panel - once disabled here you should not longer receive this error message. If you can't disable PayPal from the control panel you might have to contact Braintree support.

The `getPaymentFormHtml()` is a method on the gateway that you access from your twig templates. If you've managed to get the Dropin-UI displaying you're probably already it. Further details can be found here - https://docs.craftcms.com/commerce/v2/making-payments.html
