### ISSUE TITLE
Unable to complete a transaction using the plug-in

### ISSUE THREAD

**Issue by baronetto** [KuriousAgency/commerce-braintree#21]
Hello,

I have setup the plugin using sandbox credentials. The drop-in appears as expected (with a Paypal not linked error). I select "Credit card" and then enter the test credit card details and the card seems to be tokenised without a problem but the "Purchase" button is disabled so I cannot complete the transaction.

Can you please help?

**Comment by mcjackson18** [comment]
Hi @baronetto,

I'm unable to replicate this bug. Can you get back to me on the following:

1. Are you using the latest version of the plugin (2.2.7)?
2. Can you confirm you are you using test cards from here - https://developers.braintreepayments.com/guides/credit-cards/testing-go-live/php
3. Can you include the payment form code you are using, including any options passed to `gateway.getPaymentFormHtml()`

**Comment by focalinteractive** [comment]
Hi @mcjackson18 !

1. Yes, I can confirm that I'm using v.2.2.7
2. I have enabled 3D Secure so I'm using the cards in this link: https://developers.braintreepayments.com/files/Centinel.IntegrationGuide.ConsumerAuthentication_TestCases_v1_18_0_20160823.pdf 
3. The code is below:
```

**Comment by baronetto** [comment]
Hi @mcjackson18 !

1. Yes, I can confirm that I'm using v.2.2.7
2. I have enabled 3D Secure so I'm using the cards in this link: https://developers.braintreepayments.com/files/Centinel.IntegrationGuide.ConsumerAuthentication_TestCases_v1_18_0_20160823.pdf 
3. The code is below:
```
{{ cart.gateway.getPaymentFormHtml({threeDSecure:true})|raw }}
```

I'm posting a screenshot from the demo templates (I get the same error on the final templates)
Can I send a video capture of all the steps on a non-public address?

<img width="1216" alt="Screenshot 2019-11-25 at 18 38 54" src="https://user-images.githubusercontent.com/8502160/69559782-3f131800-0fb3-11ea-99b1-70cc586f8114.png">

**Comment by mcjackson18** [comment]
After further investigation this looks like an integration problem rather than an issue with plugin.
