### ISSUE TITLE
[Feature Request] Allow `testMode` to be set to an environment variable

### ISSUE THREAD

**Issue by benface** [KuriousAgency/commerce-braintree#28]
In the gateway settings stored in the project config, I would like to be able to set `testMode` to an environment variable, e.g. `$BRAINTREE_TEST_MODE`. It looks like Craft supports boolean strings (`"true"` / `"false"`) in environment variables: https://github.com/craftcms/cms/issues/3975

I would like to change the value of Merchant ID, Public Key and Private Key based on the environment (so locally they are set to the sandbox credentials, but on the production server they are set to the live ones), but that doesn't work if the value of "Test" has to be hardcoded in the project config.

**Comment by mcjackson18** [comment]
@benface at the moment this can be done using the commerce-gateways.php config file (see https://docs.craftcms.com/commerce/v2/payment-gateways.html#storing-config-outside-of-the-database). 

Example of how to set this up:

```
<?php

return [
	'braintree' => [
		'merchantId' => getenv('BRAINTREE_MERCHANT_ID'),
		'publicKey' => getenv('BRAINTREE_PUBLIC_KEY'),
		'privateKey' => getenv('BRAINTREE_PRIVATE_KEY'),
		'testMode' => getenv('BRAINTREE_TESTMODE'),
	],
];
```

In your production .env file exclude the BRAINTREE_TESTMODE variable - don't set to true you need to omit it altogether, so you just have the following variables:

```
BRAINTREE_MERCHANT_ID
BRAINTREE_PUBLIC_KEY
BRAINTREE_PRIVATE_KEY
```

**Comment by benface** [comment]
Ah yes, I had forgotten about that Commerce feature, thanks @mcjackson18! I did it like this:

```php
<?php

return [
    'braintree' => [
        'testMode' => (bool)getenv('BRAINTREE_TEST_MODE'),
    ],
];
```

and then in `.env` in local dev/staging:

```
BRAINTREE_TEST_MODE=1
```

and in production:

```
BRAINTREE_TEST_MODE=0
```
