### ISSUE TITLE
Bug: merchantAccountId set to NULL if only one currency is availabe

### ISSUE THREAD

**Issue by mizmiz** [KuriousAgency/commerce-braintree#29]
**Env**
craftcms/cms 3.4.15
craftcms/commerce 3.1.2
kuriousagency/commerce-braintree 2.3.5

**Steps to reproduce**
1. Go to Commerce > Store Settings > Payment Currencies and remove all currencies in but EUR 
2. Go to Commerce > System Settings > Gateways > Braintree Gateway

**Expected**
Field "EUR Merchant Account Id"

**Actual**
No field for Merchant Account Id

**Hint**
After clicking "Save" button the value for "merchantAccountId" is set to NULL (See project.yaml)

**Possible Solution**
Remove condition "{% if currencies|length > 1 %}" in src/templates/gatewaySettings.twig

**Comment by jakubjo** [comment]
Workaround: Setting it directly in project.yaml seems to work.

![image](https://user-images.githubusercontent.com/2873852/82313733-0e8fc200-99c9-11ea-9f51-7074a5db8842.png)

**Comment by BrandonJamesBorders** [comment]
@samuelbirch Any official bugfix on the way for this?

**Comment by samuelbirch** [comment]
@BrandonJamesBorders I've got 2 possible options to resolve this:

1. I fix the issue and go with the intended functionality of if only once currency we don't pass in the merchantAccountId so Braintree will use the default merchant account.

2. We go with your solution of allowing a merchantAccountId to be specified for a single currency. I can see benefits of this making it easy to switch between accounts if desired, but not as simple for a basic setup.

Do you have any opinions on this?

**Comment by samuelbirch** [comment]
fixed in 2.3.6

**Comment by BrandonJamesBorders** [comment]
@samuelbirch Working for me now across multiple environments. I definitely feel you made the right decision going with 2. 

Thanks! I should have another license purchase coming your way in a week or two.
