### ISSUE TITLE
Craft site locale `zh` results in drop-in ui not rending

### ISSUE THREAD

**Issue by zackspear** [KuriousAgency/commerce-braintree#33]
Setting a site in Craft to Chinese, locale `zh`, results in the Drop-in UI not rending. 

French, German, & Spanish work just fine.

Here's a low level example of it working: https://codepen.io/zackspear/pen/JjbaYzV

**Comment by mcjackson18** [comment]
Hi @zackspear, I'm unable to replicate this issue, setting the site language to zh displayed the Drop-in UI correctly (see screenshot).
![braintree-drop-in-ui-zh](https://user-images.githubusercontent.com/39083512/134640972-7d1566ea-57e2-431f-9491-8b306093bda1.png)
.

**Comment by zackspear** [comment]
Thanks for taking a look. No worries.

If I recall correctly I resorted to rolling my own Drop-in UI implementation in Vue.js which allowed me to drop the jQuery requirement. We'd been using Vue.js everywhere on the site except the payment page so this helped us clean things up dependency wise.
