### ISSUE TITLE
Add support for trial days per subscription.

### ISSUE THREAD

**Issue by digason** [KuriousAgency/commerce-braintree#40]
See pull request #34

https://github.com/KuriousAgency/commerce-braintree/pull/34

**Comment by mcjackson18** [comment]
@digason, thanks for the PR. 

Your changes have been included in the latest version. This version isn't release yet but in the meantime you can test by changing your composer.json to:

"kuriousagency/commerce-braintree": "dev-master as 2.4.2",

Then doing a composer clear-cache && composer update
