### ISSUE TITLE
Support for PayPal not working

### ISSUE THREAD

**Issue by zackspear** [KuriousAgency/commerce-braintree#6]
Thanks for the plugin!

I'm unfortunately having some issues. When calling the default `getPaymentFormHtml()` method to get the Drop-in UI I am unable to get the PayPal payment option to work.

Clicking the blue PayPal button will trigger the PayPal popup window to appear but then it quickly disappears and an error displays in the Drop-in UI, "Something went wrong on our end." and a few errors are logged in the console.

![screenshot of console](https://i.imgur.com/a0V7vsM.png)

I am on the current latest versions
- Craft CMS 3.2.10
- Craft Commerce 2.1.11
- Braintree for Craft Commerce 2.1.15

Please let me know if I need to provide additional info. Thanks in advance.

**Comment by samuelbirch** [comment]
thanks, we'll take a look

**Comment by samuelbirch** [comment]
should be fixed in 2.1.16

**Comment by zackspear** [comment]
Thanks for the swift response and fix for this.

Hate to be a further pest, but I'm having a different issue now that I've been able to progress further through the PayPal payment option.

Once the PayPal popup window is closed and the PayPal option added to the Drop-in UI, I can submit the payment but I get a response error, "US state codes must be two characters to meet PayPal Seller Protection requirements."

I'm currently using a slightly modified version of the Craft Commerce checkout example template and it uses ID's to represent the states. So I'm not sure if this issue is because of how the template is setup or something on the plugin's side.

Address I'm using for testing purposes is:
123 Main St 
Portland Oregon 
United States 97217

I was able to successfully make a PayPal purchase when using an address in a country that doesn't have a state.

**Comment by samuelbirch** [comment]
this should now be working in 2.1.17

**Comment by zackspear** [comment]
Thank you @samuelbirch 👍

**Comment by kristofferrom** [comment]
I'm experiencing this on 7.x-3.0 too.
